name: right

dynamixel:
  # USB port name given by the command: ls /dev/serial/by-id/
  dynamixel_port: "usb-FTDI_USB__-__Serial_Converter_FTAA0B2I-if00-port0" # edited on Jun 17
  # Servo types
  servo_types: [
    "XC330_T288_T", "XM430_W210_T", "XC330_T288_T", "XM430_W210_T", 
    "XC330_T288_T", "XC330_T288_T", "XC330_T288_T", "XC330_T288_T",
  ]
  # Servo joint directions to match that of the leader arm
  joint_signs: [1, 1, -1, 1, 1, -1, 1, -1]
  
arm_teleop:
  # URDF used for creating leader arm dynamics model to compute gravity compensation
  leader_urdf: "flexivv3_jointconfig.urdf" # TODO
  num_arm_joints: 7
  arm_joint_limits_max: [4.5, 4.131, 6, 6, 8, 7.77, 3.32]  
  arm_joint_limits_min: [-0.5, -4.5, -3, -6, -4, -4, -3.32] # THIS DOES NOT INCLUDE THE TRIGGER!  
  arm_joint_limits_safety_margin: 0.1
  initialization:
    # The expected leader arm jo0int position before launching the script
    calibration_joint_pos: [0., -0, 0.0, 0, 0, 0, 0] 
    # The arm needs to be held in a certain position before launching!
    # More information in the README.md file!
    # The leader arm must be brought to this joint position before the follower starts mirroring the leader
    initial_match_joint_pos: [0.0, -0, 0.0, 0, 0, 0, 0]
  
gripper_teleop:
  # The maximum range (in rad) of the leader gripper trigger
  actuation_range: 10

controller:
  frequency: 500
  torque_feedback:
    enable: True
    gain: 3.0
    damping: 0.0
    motor_scalar: 94.5652173913
  gravity_comp:
    enable: True
    gain: 700
  null_space_regulation:
    null_space_joint_target: [0.0, -0.7854, 0.0, -2.356, 0.0, 1.57, 0.0, 0.0]
    kp: 0.1
    kd: 0.01
  static_friction_comp:
    enable_speed: 0.9
    gain: 0.6
  joint_limit_barrier:
    kp: 1.03561658022
    kd: 0.04315069084
  joint_position_control:
    interpolation_step_size: 0.5
    kp: 1.03561658022
    kd: 0.04315069084

  gripper_feedback:
    enable: True
    gain: 0.28328611898
    ema_beta: 0.95
